#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'hps_dds_wrapper' in
 * file './hps_dds_wrapper.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'wrapper_data_0', class 'wrapper_data'
 * The macros are prefixed with 'WRAPPER_DATA_0_'.
 * The prefix is the slave descriptor.
 */
#define WRAPPER_DATA_0_COMPONENT_TYPE wrapper_data
#define WRAPPER_DATA_0_COMPONENT_NAME wrapper_data_0
#define WRAPPER_DATA_0_BASE 0x0
#define WRAPPER_DATA_0_SPAN 256
#define WRAPPER_DATA_0_END 0xff

/*
 * Macros for device 'wrapper_address_0', class 'wrapper_address'
 * The macros are prefixed with 'WRAPPER_ADDRESS_0_'.
 * The prefix is the slave descriptor.
 */
#define WRAPPER_ADDRESS_0_COMPONENT_TYPE wrapper_address
#define WRAPPER_ADDRESS_0_COMPONENT_NAME wrapper_address_0
#define WRAPPER_ADDRESS_0_BASE 0x100
#define WRAPPER_ADDRESS_0_SPAN 16
#define WRAPPER_ADDRESS_0_END 0x10f

/*
 * Macros for device 'wrapper_ctrl_0', class 'wrapper_ctrl'
 * The macros are prefixed with 'WRAPPER_CTRL_0_'.
 * The prefix is the slave descriptor.
 */
#define WRAPPER_CTRL_0_COMPONENT_TYPE wrapper_ctrl
#define WRAPPER_CTRL_0_COMPONENT_NAME wrapper_ctrl_0
#define WRAPPER_CTRL_0_BASE 0x110
#define WRAPPER_CTRL_0_SPAN 16
#define WRAPPER_CTRL_0_END 0x11f


#endif /* _ALTERA_HPS_0_H_ */
