	hps_dds_wrapper u0 (
		.address_0_adc_address_export          (<connected-to-address_0_adc_address_export>),          //          address_0_adc_address.export
		.address_0_chrono2_address_export      (<connected-to-address_0_chrono2_address_export>),      //      address_0_chrono2_address.export
		.address_0_chrono_address_export       (<connected-to-address_0_chrono_address_export>),       //       address_0_chrono_address.export
		.address_0_debug_address_in_export     (<connected-to-address_0_debug_address_in_export>),     //     address_0_debug_address_in.export
		.address_0_ftw_address_export          (<connected-to-address_0_ftw_address_export>),          //          address_0_ftw_address.export
		.address_0_init_address_export         (<connected-to-address_0_init_address_export>),         //         address_0_init_address.export
		.address_0_modulation_address_export   (<connected-to-address_0_modulation_address_export>),   //   address_0_modulation_address.export
		.address_0_ptw_address_export          (<connected-to-address_0_ptw_address_export>),          //          address_0_ptw_address.export
		.address_0_pulse_pgr_address_export    (<connected-to-address_0_pulse_pgr_address_export>),    //    address_0_pulse_pgr_address.export
		.clk_clk                               (<connected-to-clk_clk>),                               //                            clk.clk
		.ctrl_0_adc_ctrlreg_out_export         (<connected-to-ctrl_0_adc_ctrlreg_out_export>),         //         ctrl_0_adc_ctrlreg_out.export
		.ctrl_0_chrono2_ctrlreg_out_readdata   (<connected-to-ctrl_0_chrono2_ctrlreg_out_readdata>),   //     ctrl_0_chrono2_ctrlreg_out.readdata
		.ctrl_0_chrono_ctrlreg_out_export      (<connected-to-ctrl_0_chrono_ctrlreg_out_export>),      //      ctrl_0_chrono_ctrlreg_out.export
		.ctrl_0_debug_ctrl_in_export           (<connected-to-ctrl_0_debug_ctrl_in_export>),           //           ctrl_0_debug_ctrl_in.export
		.ctrl_0_debug_ctrlreg_out_export       (<connected-to-ctrl_0_debug_ctrlreg_out_export>),       //       ctrl_0_debug_ctrlreg_out.export
		.ctrl_0_endfsm_ctrl_flag_in_export     (<connected-to-ctrl_0_endfsm_ctrl_flag_in_export>),     //     ctrl_0_endfsm_ctrl_flag_in.export
		.ctrl_0_ftw_ctrlreg_out_export         (<connected-to-ctrl_0_ftw_ctrlreg_out_export>),         //         ctrl_0_ftw_ctrlreg_out.export
		.ctrl_0_init_ctrlreg_out_export        (<connected-to-ctrl_0_init_ctrlreg_out_export>),        //        ctrl_0_init_ctrlreg_out.export
		.ctrl_0_modulation_ctrlreg_out_export  (<connected-to-ctrl_0_modulation_ctrlreg_out_export>),  //  ctrl_0_modulation_ctrlreg_out.export
		.ctrl_0_outmux_ctrlreg_export          (<connected-to-ctrl_0_outmux_ctrlreg_export>),          //          ctrl_0_outmux_ctrlreg.export
		.ctrl_0_ptw_ctrlreg_out_export         (<connected-to-ctrl_0_ptw_ctrlreg_out_export>),         //         ctrl_0_ptw_ctrlreg_out.export
		.ctrl_0_pulse_pgr_ctrlreg_export       (<connected-to-ctrl_0_pulse_pgr_ctrlreg_export>),       //       ctrl_0_pulse_pgr_ctrlreg.export
		.data_0_adc_ram_data_export            (<connected-to-data_0_adc_ram_data_export>),            //            data_0_adc_ram_data.export
		.data_0_chrono2_ram_data_export        (<connected-to-data_0_chrono2_ram_data_export>),        //        data_0_chrono2_ram_data.export
		.data_0_chrono_ram_data_out_export     (<connected-to-data_0_chrono_ram_data_out_export>),     //     data_0_chrono_ram_data_out.export
		.data_0_debug_data_in_export           (<connected-to-data_0_debug_data_in_export>),           //           data_0_debug_data_in.export
		.data_0_debug_ram_data_out_export      (<connected-to-data_0_debug_ram_data_out_export>),      //      data_0_debug_ram_data_out.export
		.data_0_ftw_ram_data_out_export        (<connected-to-data_0_ftw_ram_data_out_export>),        //        data_0_ftw_ram_data_out.export
		.data_0_init_ram_data_out_export       (<connected-to-data_0_init_ram_data_out_export>),       //       data_0_init_ram_data_out.export
		.data_0_modulation_ram_data_out_export (<connected-to-data_0_modulation_ram_data_out_export>), // data_0_modulation_ram_data_out.export
		.data_0_ptw_ram_data_out_export        (<connected-to-data_0_ptw_ram_data_out_export>),        //        data_0_ptw_ram_data_out.export
		.data_0_pulse_pgr_ram_data_export      (<connected-to-data_0_pulse_pgr_ram_data_export>),      //      data_0_pulse_pgr_ram_data.export
		.data_0_rd_ramout_adc_export           (<connected-to-data_0_rd_ramout_adc_export>),           //           data_0_rd_ramout_adc.export
		.data_0_rd_ramout_chrono2_export       (<connected-to-data_0_rd_ramout_chrono2_export>),       //       data_0_rd_ramout_chrono2.export
		.data_0_rd_ramout_chrono_in_export     (<connected-to-data_0_rd_ramout_chrono_in_export>),     //     data_0_rd_ramout_chrono_in.export
		.data_0_rd_ramout_ftw_in_export        (<connected-to-data_0_rd_ramout_ftw_in_export>),        //        data_0_rd_ramout_ftw_in.export
		.data_0_rd_ramout_init_in_export       (<connected-to-data_0_rd_ramout_init_in_export>),       //       data_0_rd_ramout_init_in.export
		.data_0_rd_ramout_modulation_in_export (<connected-to-data_0_rd_ramout_modulation_in_export>), // data_0_rd_ramout_modulation_in.export
		.data_0_rd_ramout_ptw_in_export        (<connected-to-data_0_rd_ramout_ptw_in_export>),        //        data_0_rd_ramout_ptw_in.export
		.data_0_rd_ramout_pulse_pgr_export     (<connected-to-data_0_rd_ramout_pulse_pgr_export>),     //     data_0_rd_ramout_pulse_pgr.export
		.hps_0_h2f_reset_reset_n               (<connected-to-hps_0_h2f_reset_reset_n>),               //                hps_0_h2f_reset.reset_n
		.hps_io_hps_io_emac1_inst_TX_CLK       (<connected-to-hps_io_hps_io_emac1_inst_TX_CLK>),       //                         hps_io.hps_io_emac1_inst_TX_CLK
		.hps_io_hps_io_emac1_inst_TXD0         (<connected-to-hps_io_hps_io_emac1_inst_TXD0>),         //                               .hps_io_emac1_inst_TXD0
		.hps_io_hps_io_emac1_inst_TXD1         (<connected-to-hps_io_hps_io_emac1_inst_TXD1>),         //                               .hps_io_emac1_inst_TXD1
		.hps_io_hps_io_emac1_inst_TXD2         (<connected-to-hps_io_hps_io_emac1_inst_TXD2>),         //                               .hps_io_emac1_inst_TXD2
		.hps_io_hps_io_emac1_inst_TXD3         (<connected-to-hps_io_hps_io_emac1_inst_TXD3>),         //                               .hps_io_emac1_inst_TXD3
		.hps_io_hps_io_emac1_inst_RXD0         (<connected-to-hps_io_hps_io_emac1_inst_RXD0>),         //                               .hps_io_emac1_inst_RXD0
		.hps_io_hps_io_emac1_inst_MDIO         (<connected-to-hps_io_hps_io_emac1_inst_MDIO>),         //                               .hps_io_emac1_inst_MDIO
		.hps_io_hps_io_emac1_inst_MDC          (<connected-to-hps_io_hps_io_emac1_inst_MDC>),          //                               .hps_io_emac1_inst_MDC
		.hps_io_hps_io_emac1_inst_RX_CTL       (<connected-to-hps_io_hps_io_emac1_inst_RX_CTL>),       //                               .hps_io_emac1_inst_RX_CTL
		.hps_io_hps_io_emac1_inst_TX_CTL       (<connected-to-hps_io_hps_io_emac1_inst_TX_CTL>),       //                               .hps_io_emac1_inst_TX_CTL
		.hps_io_hps_io_emac1_inst_RX_CLK       (<connected-to-hps_io_hps_io_emac1_inst_RX_CLK>),       //                               .hps_io_emac1_inst_RX_CLK
		.hps_io_hps_io_emac1_inst_RXD1         (<connected-to-hps_io_hps_io_emac1_inst_RXD1>),         //                               .hps_io_emac1_inst_RXD1
		.hps_io_hps_io_emac1_inst_RXD2         (<connected-to-hps_io_hps_io_emac1_inst_RXD2>),         //                               .hps_io_emac1_inst_RXD2
		.hps_io_hps_io_emac1_inst_RXD3         (<connected-to-hps_io_hps_io_emac1_inst_RXD3>),         //                               .hps_io_emac1_inst_RXD3
		.hps_io_hps_io_sdio_inst_CMD           (<connected-to-hps_io_hps_io_sdio_inst_CMD>),           //                               .hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0            (<connected-to-hps_io_hps_io_sdio_inst_D0>),            //                               .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1            (<connected-to-hps_io_hps_io_sdio_inst_D1>),            //                               .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK           (<connected-to-hps_io_hps_io_sdio_inst_CLK>),           //                               .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2            (<connected-to-hps_io_hps_io_sdio_inst_D2>),            //                               .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3            (<connected-to-hps_io_hps_io_sdio_inst_D3>),            //                               .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0            (<connected-to-hps_io_hps_io_usb1_inst_D0>),            //                               .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1            (<connected-to-hps_io_hps_io_usb1_inst_D1>),            //                               .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2            (<connected-to-hps_io_hps_io_usb1_inst_D2>),            //                               .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3            (<connected-to-hps_io_hps_io_usb1_inst_D3>),            //                               .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4            (<connected-to-hps_io_hps_io_usb1_inst_D4>),            //                               .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5            (<connected-to-hps_io_hps_io_usb1_inst_D5>),            //                               .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6            (<connected-to-hps_io_hps_io_usb1_inst_D6>),            //                               .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7            (<connected-to-hps_io_hps_io_usb1_inst_D7>),            //                               .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK           (<connected-to-hps_io_hps_io_usb1_inst_CLK>),           //                               .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP           (<connected-to-hps_io_hps_io_usb1_inst_STP>),           //                               .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR           (<connected-to-hps_io_hps_io_usb1_inst_DIR>),           //                               .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT           (<connected-to-hps_io_hps_io_usb1_inst_NXT>),           //                               .hps_io_usb1_inst_NXT
		.hps_io_hps_io_uart0_inst_RX           (<connected-to-hps_io_hps_io_uart0_inst_RX>),           //                               .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX           (<connected-to-hps_io_hps_io_uart0_inst_TX>),           //                               .hps_io_uart0_inst_TX
		.hps_io_hps_io_gpio_inst_GPIO09        (<connected-to-hps_io_hps_io_gpio_inst_GPIO09>),        //                               .hps_io_gpio_inst_GPIO09
		.hps_io_hps_io_gpio_inst_GPIO35        (<connected-to-hps_io_hps_io_gpio_inst_GPIO35>),        //                               .hps_io_gpio_inst_GPIO35
		.hps_io_hps_io_gpio_inst_GPIO53        (<connected-to-hps_io_hps_io_gpio_inst_GPIO53>),        //                               .hps_io_gpio_inst_GPIO53
		.hps_io_hps_io_gpio_inst_GPIO54        (<connected-to-hps_io_hps_io_gpio_inst_GPIO54>),        //                               .hps_io_gpio_inst_GPIO54
		.memory_mem_a                          (<connected-to-memory_mem_a>),                          //                         memory.mem_a
		.memory_mem_ba                         (<connected-to-memory_mem_ba>),                         //                               .mem_ba
		.memory_mem_ck                         (<connected-to-memory_mem_ck>),                         //                               .mem_ck
		.memory_mem_ck_n                       (<connected-to-memory_mem_ck_n>),                       //                               .mem_ck_n
		.memory_mem_cke                        (<connected-to-memory_mem_cke>),                        //                               .mem_cke
		.memory_mem_cs_n                       (<connected-to-memory_mem_cs_n>),                       //                               .mem_cs_n
		.memory_mem_ras_n                      (<connected-to-memory_mem_ras_n>),                      //                               .mem_ras_n
		.memory_mem_cas_n                      (<connected-to-memory_mem_cas_n>),                      //                               .mem_cas_n
		.memory_mem_we_n                       (<connected-to-memory_mem_we_n>),                       //                               .mem_we_n
		.memory_mem_reset_n                    (<connected-to-memory_mem_reset_n>),                    //                               .mem_reset_n
		.memory_mem_dq                         (<connected-to-memory_mem_dq>),                         //                               .mem_dq
		.memory_mem_dqs                        (<connected-to-memory_mem_dqs>),                        //                               .mem_dqs
		.memory_mem_dqs_n                      (<connected-to-memory_mem_dqs_n>),                      //                               .mem_dqs_n
		.memory_mem_odt                        (<connected-to-memory_mem_odt>),                        //                               .mem_odt
		.memory_mem_dm                         (<connected-to-memory_mem_dm>),                         //                               .mem_dm
		.memory_oct_rzqin                      (<connected-to-memory_oct_rzqin>),                      //                               .oct_rzqin
		.reset_reset_n                         (<connected-to-reset_reset_n>)                          //                          reset.reset_n
	);

