// Copyright (C) 2023  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 22.1 (Build Build 917 02/14/2023)
// Created on Mon Oct 21 11:34:36 2024

fsm_pwt_write_v2 fsm_pwt_write_v2_inst
(
	.clk_fsm_ptw(clk_fsm_ptw_sig) ,	// input  clk_fsm_ptw_sig
	.rst_n_fsm_ptw(rst_n_fsm_ptw_sig) ,	// input  rst_n_fsm_ptw_sig
	.start_fsm_ptw(start_fsm_ptw_sig) ,	// input  start_fsm_ptw_sig
	.AddressMem_offset(AddressMem_offset_sig) ,	// input [5:0] AddressMem_offset_sig
	.rd_PTWMem(rd_PTWMem_sig) ,	// output  rd_PTWMem_sig
	.wr_PTWMem(wr_PTWMem_sig) ,	// output  wr_PTWMem_sig
	.en_PTWMem(en_PTWMem_sig) ,	// output  en_PTWMem_sig
	.clc_PTWMem(clc_PTWMem_sig) ,	// output  clc_PTWMem_sig
	.addressPTWMemtMem(addressPTWMemtMem_sig) ,	// output [5:0] addressPTWMemtMem_sig
	.fsm_PTWEND(fsm_PTWEND_sig) ,	// output  fsm_PTWEND_sig
	.masterRst_dds(masterRst_dds_sig) ,	// output  masterRst_dds_sig
	.rd_n_dds(rd_n_dds_sig) ,	// output  rd_n_dds_sig
	.wd_n_dds(wd_n_dds_sig) ,	// output  wd_n_dds_sig
	.FSK_BPSK_HOLD_dds(FSK_BPSK_HOLD_dds_sig) ,	// output  FSK_BPSK_HOLD_dds_sig
	.I_O_update_dds(I_O_update_dds_sig) 	// output  I_O_update_dds_sig
);

